[package]
name = "test-kernel"
version = "0.1.0"
edition = "2021"

[dependencies.ostd]
git = "https://github.com/asterinas/asterinas"
rev = "96efd62"

[dependencies]
align_ext= "0.1.0"

[workspace]
exclude = ["target/osdk/base"]
